FROM node:20-alpine AS build
WORKDIR /app
ENV NODE_OPTIONS="--max-old-space-size=512"
COPY app/frontend/package*.json ./
RUN npm install --legacy-peer-deps
COPY app/frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# Copy custom Nginx config to handle React Router and API proxying
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
