apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  # In a real environment, this is injected by Vault.
  # url: "postgres://postgres:<DB_PASSWORD>@<RDS_ENDPOINT>:5432/commerce"
  url: "postgres://postgres:YourSuperSecurePassword123!@terraform-2026061410204477150000000e.cl2ka8uaql43.ap-south-1.rds.amazonaws.com:5432/commerce"
