apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  # In a real environment, this is injected by Vault.
  # url: "postgres://postgres:<DB_PASSWORD>@<RDS_ENDPOINT>:5432/commerce"
  url: "postgres://postgres:SECRET_PASSWORD@RDS_ENDPOINT_URL:5432/commerce"
